version: '3.8'

services:
  mindful-motion:
    build:
      context: ..                 
      dockerfile: Docker/Dockerfile
      platforms:
        - linux/amd64 #for ecs
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    restart: unless-stopped